DELETE FROM AdmissionHistory;
Delete from PatientRegistration;
Delete from DeviceRepository;
Delete from DefaultLimits;
Delete from CustomLimits;
Delete from DoctorRepository;
Delete from HospitalBedRepository;
Delete from PatientAdmission;
Delete from PatientDevices;
