//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.AdditionalMonitoringClient.AdditionalDoctorDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/Models.Patient")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BloodTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmergencyContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.AdmissionHistory[] PreviousAdmissionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BloodType {
            get {
                return this.BloodTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BloodTypeField, value) != true)) {
                    this.BloodTypeField = value;
                    this.RaisePropertyChanged("BloodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmergencyContact {
            get {
                return this.EmergencyContactField;
            }
            set {
                if ((this.EmergencyContactField.Equals(value) != true)) {
                    this.EmergencyContactField = value;
                    this.RaisePropertyChanged("EmergencyContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.AdmissionHistory[] PreviousAdmissions {
            get {
                return this.PreviousAdmissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousAdmissionsField, value) != true)) {
                    this.PreviousAdmissionsField = value;
                    this.RaisePropertyChanged("PreviousAdmissions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdmissionHistory", Namespace="http://schemas.datacontract.org/2004/07/Models.Patient")]
    [System.SerializableAttribute()]
    public partial class AdmissionHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmissionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IllnessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmissionDate {
            get {
                return this.AdmissionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmissionDateField, value) != true)) {
                    this.AdmissionDateField = value;
                    this.RaisePropertyChanged("AdmissionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnosis {
            get {
                return this.DiagnosisField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosisField, value) != true)) {
                    this.DiagnosisField = value;
                    this.RaisePropertyChanged("Diagnosis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Illness {
            get {
                return this.IllnessField;
            }
            set {
                if ((object.ReferenceEquals(this.IllnessField, value) != true)) {
                    this.IllnessField = value;
                    this.RaisePropertyChanged("Illness");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientAdmission", Namespace="http://schemas.datacontract.org/2004/07/Models.PatientAdmission")]
    [System.SerializableAttribute()]
    public partial class PatientAdmission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmissionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.HospitalBed BedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Device[] DevicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IllnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MuteAlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmissionTime {
            get {
                return this.AdmissionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmissionTimeField, value) != true)) {
                    this.AdmissionTimeField = value;
                    this.RaisePropertyChanged("AdmissionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.HospitalBed Bed {
            get {
                return this.BedField;
            }
            set {
                if ((object.ReferenceEquals(this.BedField, value) != true)) {
                    this.BedField = value;
                    this.RaisePropertyChanged("Bed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Device[] Devices {
            get {
                return this.DevicesField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicesField, value) != true)) {
                    this.DevicesField = value;
                    this.RaisePropertyChanged("Devices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnosis {
            get {
                return this.DiagnosisField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosisField, value) != true)) {
                    this.DiagnosisField = value;
                    this.RaisePropertyChanged("Diagnosis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorIdField, value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Illness {
            get {
                return this.IllnessField;
            }
            set {
                if ((object.ReferenceEquals(this.IllnessField, value) != true)) {
                    this.IllnessField = value;
                    this.RaisePropertyChanged("Illness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MuteAlert {
            get {
                return this.MuteAlertField;
            }
            set {
                if ((this.MuteAlertField.Equals(value) != true)) {
                    this.MuteAlertField = value;
                    this.RaisePropertyChanged("MuteAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HospitalBed", Namespace="http://schemas.datacontract.org/2004/07/Models.HospitalBed")]
    [System.SerializableAttribute()]
    public partial class HospitalBed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BedNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupancyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BedNumber {
            get {
                return this.BedNumberField;
            }
            set {
                if ((this.BedNumberField.Equals(value) != true)) {
                    this.BedNumberField = value;
                    this.RaisePropertyChanged("BedNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupancy {
            get {
                return this.OccupancyField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupancyField, value) != true)) {
                    this.OccupancyField = value;
                    this.RaisePropertyChanged("Occupancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wing {
            get {
                return this.WingField;
            }
            set {
                if ((object.ReferenceEquals(this.WingField, value) != true)) {
                    this.WingField = value;
                    this.RaisePropertyChanged("Wing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/Models.Device")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Limits[] LimitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxInputValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinInputValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Limits[] Limits {
            get {
                return this.LimitsField;
            }
            set {
                if ((object.ReferenceEquals(this.LimitsField, value) != true)) {
                    this.LimitsField = value;
                    this.RaisePropertyChanged("Limits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxInputValue {
            get {
                return this.MaxInputValueField;
            }
            set {
                if ((this.MaxInputValueField.Equals(value) != true)) {
                    this.MaxInputValueField = value;
                    this.RaisePropertyChanged("MaxInputValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinInputValue {
            get {
                return this.MinInputValueField;
            }
            set {
                if ((this.MinInputValueField.Equals(value) != true)) {
                    this.MinInputValueField = value;
                    this.RaisePropertyChanged("MinInputValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Limits", Namespace="http://schemas.datacontract.org/2004/07/Models.Device")]
    [System.SerializableAttribute()]
    public partial class Limits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxValue {
            get {
                return this.MaxValueField;
            }
            set {
                if ((this.MaxValueField.Equals(value) != true)) {
                    this.MaxValueField = value;
                    this.RaisePropertyChanged("MaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinValue {
            get {
                return this.MinValueField;
            }
            set {
                if ((this.MinValueField.Equals(value) != true)) {
                    this.MinValueField = value;
                    this.RaisePropertyChanged("MinValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/Models.Doctor")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PatientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorIdField, value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Patients {
            get {
                return this.PatientsField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsField, value) != true)) {
                    this.PatientsField = value;
                    this.RaisePropertyChanged("Patients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdditionalDoctorDataService.IAdditionalDoctorDataService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAdditionalDoctorDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientRegistrations", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientRegistrationsRespon" +
            "se")]
        Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient[] ReadAllPatientRegistrations(string doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientRegistrations", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientRegistrationsRespon" +
            "se")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient[]> ReadAllPatientRegistrationsAsync(string doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientRegistration", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientRegistrationResponse")]
        Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient ReadPatientRegistration(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientRegistration", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientRegistrationResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient> ReadPatientRegistrationAsync(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientAdmissions", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientAdmissionsResponse")]
        Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission[] ReadAllPatientAdmissions(string doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientAdmissions", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadAllPatientAdmissionsResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission[]> ReadAllPatientAdmissionsAsync(string doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientAdmission", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientAdmissionResponse")]
        Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission ReadPatientAdmission(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientAdmission", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadPatientAdmissionResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission> ReadPatientAdmissionAsync(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadAllDoctors", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadAllDoctorsResponse")]
        Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor[] ReadAllDoctors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadAllDoctors", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadAllDoctorsResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor[]> ReadAllDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadDoctor", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadDoctorResponse")]
        Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor ReadDoctor(string doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalDoctorDataService/ReadDoctor", ReplyAction="http://tempuri.org/IAdditionalDoctorDataService/ReadDoctorResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor> ReadDoctorAsync(string doctorId);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdditionalDoctorDataService/UpdateDoctorStatus")]
        void UpdateDoctorStatus(Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdditionalDoctorDataService/UpdateDoctorStatus")]
        System.Threading.Tasks.Task UpdateDoctorStatusAsync(Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDoctorStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDoctorStatus", Namespace="http://tempuri.org/", Order=0)]
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatusBody Body;
        
        public UpdateDoctorStatus() {
        }
        
        public UpdateDoctorStatus(Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDoctorStatusBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public UpdateDoctorStatusBody() {
        }
        
        public UpdateDoctorStatusBody(string doctorId, string status) {
            this.doctorId = doctorId;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdditionalDoctorDataServiceChannel : Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditionalDoctorDataServiceClient : System.ServiceModel.ClientBase<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService>, Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService {
        
        public AdditionalDoctorDataServiceClient() {
        }
        
        public AdditionalDoctorDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditionalDoctorDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionalDoctorDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionalDoctorDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient[] ReadAllPatientRegistrations(string doctorId) {
            return base.Channel.ReadAllPatientRegistrations(doctorId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient[]> ReadAllPatientRegistrationsAsync(string doctorId) {
            return base.Channel.ReadAllPatientRegistrationsAsync(doctorId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient ReadPatientRegistration(string patientId) {
            return base.Channel.ReadPatientRegistration(patientId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Patient> ReadPatientRegistrationAsync(string patientId) {
            return base.Channel.ReadPatientRegistrationAsync(patientId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission[] ReadAllPatientAdmissions(string doctorId) {
            return base.Channel.ReadAllPatientAdmissions(doctorId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission[]> ReadAllPatientAdmissionsAsync(string doctorId) {
            return base.Channel.ReadAllPatientAdmissionsAsync(doctorId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission ReadPatientAdmission(string patientId) {
            return base.Channel.ReadPatientAdmission(patientId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.PatientAdmission> ReadPatientAdmissionAsync(string patientId) {
            return base.Channel.ReadPatientAdmissionAsync(patientId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor[] ReadAllDoctors() {
            return base.Channel.ReadAllDoctors();
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor[]> ReadAllDoctorsAsync() {
            return base.Channel.ReadAllDoctorsAsync();
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor ReadDoctor(string doctorId) {
            return base.Channel.ReadDoctor(doctorId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.Doctor> ReadDoctorAsync(string doctorId) {
            return base.Channel.ReadDoctorAsync(doctorId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService.UpdateDoctorStatus(Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus request) {
            base.Channel.UpdateDoctorStatus(request);
        }
        
        public void UpdateDoctorStatus(string doctorId, string status) {
            Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus inValue = new Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus();
            inValue.Body = new Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatusBody();
            inValue.Body.doctorId = doctorId;
            inValue.Body.status = status;
            ((Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService)(this)).UpdateDoctorStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService.UpdateDoctorStatusAsync(Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus request) {
            return base.Channel.UpdateDoctorStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task UpdateDoctorStatusAsync(string doctorId, string status) {
            Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus inValue = new Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatus();
            inValue.Body = new Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.UpdateDoctorStatusBody();
            inValue.Body.doctorId = doctorId;
            inValue.Body.status = status;
            return ((Clients.AdditionalMonitoringClient.AdditionalDoctorDataService.IAdditionalDoctorDataService)(this)).UpdateDoctorStatusAsync(inValue);
        }
    }
}
