//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.AdditionalMonitoringClient.AdditionalNurseDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/Models.Patient")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BloodTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmergencyContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalNurseDataService.AdmissionHistory[] PreviousAdmissionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BloodType {
            get {
                return this.BloodTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BloodTypeField, value) != true)) {
                    this.BloodTypeField = value;
                    this.RaisePropertyChanged("BloodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmergencyContact {
            get {
                return this.EmergencyContactField;
            }
            set {
                if ((this.EmergencyContactField.Equals(value) != true)) {
                    this.EmergencyContactField = value;
                    this.RaisePropertyChanged("EmergencyContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.AdmissionHistory[] PreviousAdmissions {
            get {
                return this.PreviousAdmissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousAdmissionsField, value) != true)) {
                    this.PreviousAdmissionsField = value;
                    this.RaisePropertyChanged("PreviousAdmissions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdmissionHistory", Namespace="http://schemas.datacontract.org/2004/07/Models.Patient")]
    [System.SerializableAttribute()]
    public partial class AdmissionHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmissionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IllnessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmissionDate {
            get {
                return this.AdmissionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmissionDateField, value) != true)) {
                    this.AdmissionDateField = value;
                    this.RaisePropertyChanged("AdmissionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnosis {
            get {
                return this.DiagnosisField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosisField, value) != true)) {
                    this.DiagnosisField = value;
                    this.RaisePropertyChanged("Diagnosis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Illness {
            get {
                return this.IllnessField;
            }
            set {
                if ((object.ReferenceEquals(this.IllnessField, value) != true)) {
                    this.IllnessField = value;
                    this.RaisePropertyChanged("Illness");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientAdmission", Namespace="http://schemas.datacontract.org/2004/07/Models.PatientAdmission")]
    [System.SerializableAttribute()]
    public partial class PatientAdmission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmissionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalNurseDataService.HospitalBed BedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Device[] DevicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IllnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MuteAlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmissionTime {
            get {
                return this.AdmissionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmissionTimeField, value) != true)) {
                    this.AdmissionTimeField = value;
                    this.RaisePropertyChanged("AdmissionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.HospitalBed Bed {
            get {
                return this.BedField;
            }
            set {
                if ((object.ReferenceEquals(this.BedField, value) != true)) {
                    this.BedField = value;
                    this.RaisePropertyChanged("Bed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Device[] Devices {
            get {
                return this.DevicesField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicesField, value) != true)) {
                    this.DevicesField = value;
                    this.RaisePropertyChanged("Devices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnosis {
            get {
                return this.DiagnosisField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosisField, value) != true)) {
                    this.DiagnosisField = value;
                    this.RaisePropertyChanged("Diagnosis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorIdField, value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Illness {
            get {
                return this.IllnessField;
            }
            set {
                if ((object.ReferenceEquals(this.IllnessField, value) != true)) {
                    this.IllnessField = value;
                    this.RaisePropertyChanged("Illness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MuteAlert {
            get {
                return this.MuteAlertField;
            }
            set {
                if ((this.MuteAlertField.Equals(value) != true)) {
                    this.MuteAlertField = value;
                    this.RaisePropertyChanged("MuteAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HospitalBed", Namespace="http://schemas.datacontract.org/2004/07/Models.HospitalBed")]
    [System.SerializableAttribute()]
    public partial class HospitalBed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BedNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupancyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BedNumber {
            get {
                return this.BedNumberField;
            }
            set {
                if ((this.BedNumberField.Equals(value) != true)) {
                    this.BedNumberField = value;
                    this.RaisePropertyChanged("BedNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupancy {
            get {
                return this.OccupancyField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupancyField, value) != true)) {
                    this.OccupancyField = value;
                    this.RaisePropertyChanged("Occupancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wing {
            get {
                return this.WingField;
            }
            set {
                if ((object.ReferenceEquals(this.WingField, value) != true)) {
                    this.WingField = value;
                    this.RaisePropertyChanged("Wing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/Models.Device")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Limits[] LimitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxInputValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinInputValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Limits[] Limits {
            get {
                return this.LimitsField;
            }
            set {
                if ((object.ReferenceEquals(this.LimitsField, value) != true)) {
                    this.LimitsField = value;
                    this.RaisePropertyChanged("Limits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxInputValue {
            get {
                return this.MaxInputValueField;
            }
            set {
                if ((this.MaxInputValueField.Equals(value) != true)) {
                    this.MaxInputValueField = value;
                    this.RaisePropertyChanged("MaxInputValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinInputValue {
            get {
                return this.MinInputValueField;
            }
            set {
                if ((this.MinInputValueField.Equals(value) != true)) {
                    this.MinInputValueField = value;
                    this.RaisePropertyChanged("MinInputValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Limits", Namespace="http://schemas.datacontract.org/2004/07/Models.Device")]
    [System.SerializableAttribute()]
    public partial class Limits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxValue {
            get {
                return this.MaxValueField;
            }
            set {
                if ((this.MaxValueField.Equals(value) != true)) {
                    this.MaxValueField = value;
                    this.RaisePropertyChanged("MaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinValue {
            get {
                return this.MinValueField;
            }
            set {
                if ((this.MinValueField.Equals(value) != true)) {
                    this.MinValueField = value;
                    this.RaisePropertyChanged("MinValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/Models.Doctor")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PatientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorIdField, value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Patients {
            get {
                return this.PatientsField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsField, value) != true)) {
                    this.PatientsField = value;
                    this.RaisePropertyChanged("Patients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdditionalNurseDataService.IAdditionalNurseDataService")]
    public interface IAdditionalNurseDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientRegistrations", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientRegistrationsRespons" +
            "e")]
        Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient[] ReadAllPatientRegistrations(string locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientRegistrations", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientRegistrationsRespons" +
            "e")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient[]> ReadAllPatientRegistrationsAsync(string locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadPatientRegistration", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadPatientRegistrationResponse")]
        Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient ReadPatientRegistration(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadPatientRegistration", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadPatientRegistrationResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient> ReadPatientRegistrationAsync(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientAdmissions", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientAdmissionsResponse")]
        Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission[] ReadAllPatientAdmissions(string locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientAdmissions", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadAllPatientAdmissionsResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission[]> ReadAllPatientAdmissionsAsync(string locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadPatientAdmission", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadPatientAdmissionResponse")]
        Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission ReadPatientAdmission(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadPatientAdmission", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadPatientAdmissionResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission> ReadPatientAdmissionAsync(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadAllDoctors", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadAllDoctorsResponse")]
        Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor[] ReadAllDoctors(string locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadAllDoctors", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadAllDoctorsResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor[]> ReadAllDoctorsAsync(string locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadDoctor", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadDoctorResponse")]
        Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor ReadDoctor(string doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionalNurseDataService/ReadDoctor", ReplyAction="http://tempuri.org/IAdditionalNurseDataService/ReadDoctorResponse")]
        System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor> ReadDoctorAsync(string doctorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdditionalNurseDataServiceChannel : Clients.AdditionalMonitoringClient.AdditionalNurseDataService.IAdditionalNurseDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditionalNurseDataServiceClient : System.ServiceModel.ClientBase<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.IAdditionalNurseDataService>, Clients.AdditionalMonitoringClient.AdditionalNurseDataService.IAdditionalNurseDataService {
        
        public AdditionalNurseDataServiceClient() {
        }
        
        public AdditionalNurseDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditionalNurseDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionalNurseDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionalNurseDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient[] ReadAllPatientRegistrations(string locationId) {
            return base.Channel.ReadAllPatientRegistrations(locationId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient[]> ReadAllPatientRegistrationsAsync(string locationId) {
            return base.Channel.ReadAllPatientRegistrationsAsync(locationId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient ReadPatientRegistration(string patientId) {
            return base.Channel.ReadPatientRegistration(patientId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Patient> ReadPatientRegistrationAsync(string patientId) {
            return base.Channel.ReadPatientRegistrationAsync(patientId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission[] ReadAllPatientAdmissions(string locationId) {
            return base.Channel.ReadAllPatientAdmissions(locationId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission[]> ReadAllPatientAdmissionsAsync(string locationId) {
            return base.Channel.ReadAllPatientAdmissionsAsync(locationId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission ReadPatientAdmission(string patientId) {
            return base.Channel.ReadPatientAdmission(patientId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.PatientAdmission> ReadPatientAdmissionAsync(string patientId) {
            return base.Channel.ReadPatientAdmissionAsync(patientId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor[] ReadAllDoctors(string locationId) {
            return base.Channel.ReadAllDoctors(locationId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor[]> ReadAllDoctorsAsync(string locationId) {
            return base.Channel.ReadAllDoctorsAsync(locationId);
        }
        
        public Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor ReadDoctor(string doctorId) {
            return base.Channel.ReadDoctor(doctorId);
        }
        
        public System.Threading.Tasks.Task<Clients.AdditionalMonitoringClient.AdditionalNurseDataService.Doctor> ReadDoctorAsync(string doctorId) {
            return base.Channel.ReadDoctorAsync(doctorId);
        }
    }
}
